default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: coraline

development:
  <<: *default
  database: dungeon_delve_development

test:
  <<: *default
  database: dungeon_delve_test

production:
  <<: *default
  database: dungeon_delve_production
  pool: 25
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
